SUPABASE_URL= "https://utmilhshbqostqbuzegm.supabase.co"
SUPABASE_KEY= "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0bWlsaHNoYnFvc3RxYnV6ZWdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc1MjM0OTAsImV4cCI6MjEwMzA5OTQ5MH0.uv3FhyLK9z1yNl0oQGAOCECrseBHSOsul_oRzniu2yI"
GROQ_API_KEY= "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"
